openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/teams/{team_id}/members":
    parameters:
      - name: team_id
        in: path
        description: ID of the team
        required: true
        schema:
          type: string
    get:
      summary: List members
      tags:
        - Members
      parameters:
        - name: last_name
          in: query
          description: Search members by last name
          schema:
            type: string
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
        - name: per_page
          in: query
          description: Items per page for pagination
          schema:
            type: integer
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
    post:
      summary: Create member
      tags:
        - Members
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                user_id:
                  type: integer
              required:
                - first_name
                - last_name
                - email
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable entity
  "/teams/{team_id}/members/{id}":
    parameters:
      - name: team_id
        in: path
        description: ID of the team
        required: true
        schema:
          type: string
      - name: id
        in: path
        description: ID of the member
        required: true
        schema:
          type: string
    get:
      summary: Show member
      tags:
        - Members
      responses:
        '200':
          description: Successful
        '404':
          description: Not found
    delete:
      summary: Delete member
      tags:
        - Members
      responses:
        '204':
          description: No content
        '404':
          description: Not found
  "/teams":
    get:
      summary: List teams
      tags:
        - Teams
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          schema:
            type: integer
        - name: per_page
          in: query
          description: Items per page for pagination
          schema:
            type: integer
      responses:
        '200':
          description: Successful
        '401':
          description: Unauthorized
    post:
      summary: Create team
      tags:
        - Teams
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
                - name
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable entity
  "/teams/{id}":
    parameters:
      - name: id
        in: path
        description: ID of the team
        required: true
        schema:
          type: string
    get:
      summary: Show team
      tags:
        - Teams
      responses:
        '200':
          description: Successful
        '404':
          description: Not found
    patch:
      summary: Update team
      tags:
        - Teams
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Successful
        '404':
          description: Not found
        '422':
          description: Unprocessable entity
    delete:
      summary: Delete team
      tags:
        - Teams
      responses:
        '204':
          description: No content
        '404':
          description: Not found
  "/users/sign_up":
    post:
      summary: Create registration
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
              required:
                - email
                - password
                - password_confirmation
      responses:
        '201':
          description: Created
        '422':
          description: Unprocessable entity
  "/users/sign_in":
    post:
      summary: Create session
      tags:
        - Users
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Signed in successfully
        '401':
          description: Unauthorized
  "/users/sign_out":
    delete:
      summary: Delete session
      tags:
        - Users
      responses:
        '200':
          description: Signed out successfully
        '401':
          description: Unauthorized
  "/users/cancel":
    get:
      summary: Cancel registration
      responses:
        '200':
          description: Successful
  "/users/edit":
    get:
      summary: Edit registration
      responses:
        '200':
          description: Successful
  "/users":
    patch:
      summary: Update registration
      responses:
        '200':
          description: Successful
    put:
      summary: Update registration
      responses:
        '200':
          description: Successful
    delete:
      summary: Delete registration
      responses:
        '200':
          description: Successful
servers:
  - url: http://127.0.0.1:3000/
    variables:
      defaultHost:
        default: www.example.com
