default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: team_management_system_dev

test:
  <<: *default
  database: team_management_system_test

production:
  <<: *default
  database: team_management_system_prod
  username: team_management_system
  password: <%= ENV['PROD_DB_PASSWORD'] %>
